name: Generate Snake

on:
  schedule:
    # - cron: "0 0 * * *"
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Generate Snake
        uses: Platane/snk@v3
        id: snake-gif
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            ./images/github-snake.svg
            ./images/github-snake-dark.svg?palette=github-dark

      - name: Push to GitHub
        uses: EndBug/add-and-commit@v7.2.1
        with:
          branch: main
          message: 'Generate Snake SVG by Github Action' 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
